id: push_test_to_git
namespace: rvig.test

tasks:
  - id: commit_and_push
    type: io.kestra.plugin.git.PushFlows
    sourceNamespace: rvig.test # the namespace from which flows are pushed
    targetNamespace: rvig.test # the target production namespace; if different than sourceNamespace, the sourceNamespace in the source code will be overwritten by the targetNamespace
    flows: "*"  # optional list of glob patterns; by default, all flows are pushed
    includeChildNamespaces: true # optional boolean, false by default
    gitDirectory: _flows
    url: https://github.com/marc4gov/kestra-flows
    branch: master
    username: marc4gov
    password: "{{ secret('GITHUB_ACCESS_TOKEN') }}"
    commitMessage: "add flows {{ now() }}"
    dryRun: false  # if true, you'll see what files will be added, modified or deleted based on the state in Git without overwriting the files yet

triggers:
  - id: schedule_push
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "*/30 * * * *"