id: push_to_git
namespace: rvig.sent

tasks:
  - id: commit_and_push
    type: io.kestra.plugin.git.Push
    namespaceFiles:
      enabled: true
    flows:
      enabled: true
    url: https://github.com/marc4gov/kestra-flows
    branch: master
    username: marc4gov
    password: "{{ secret('GITHUB_ACCESS_TOKEN') }}"
    commitMessage: "add flows and scripts {{ now() }}"

triggers:
  - id: schedule_push
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "*/30 * * * *"