id: push_to_git
namespace: rvig.sent

tasks:
  - id: commit_and_push
    type: io.kestra.plugin.git.Push
    namespaceFiles:
      enabled: true
    flows:
      enabled: true
    url: https://github.com/marc4gov/kestra-flows
    branch: master
    username: marc4gov
    password: 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
    commitMessage: "add flows and scripts {{ now() }}"

triggers:
  - id: schedule_push
    type: io.kestra.core.models.triggers.types.Schedule
    cron: "*/30 * * * *"